apiVersion: v1
kind: Service
metadata:
  name: gpu-scheduler-webhook
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: gpu-scheduler-webhook
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
